[project]
name = 'Hospitality-Staff-Escrow-Wages'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Hospitality-Staff-Escrow-Wages]
path = 'contracts/Hospitality-Staff-Escrow-Wages.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
